# Generated by Django 3.2.13 on 2022-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=15)),
                ('price', models.IntegerField(default=99)),
                ('description', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=30)),
                ('fabric', models.CharField(max_length=30)),
                ('gsm', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='ProductImages/')),
            ],
        ),
    ]
